version: '3.7'
services:
  postgres:
    image: postgres:15.0
    container_name: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres-local"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - net-postgres
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres_exporter
    environment:
      - "DATA_SOURCE_NAME=postgresql://postgres:postgres-local@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - net-postgres
networks:
  net-postgres:
    driver: bridge