version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_ROOT_HOST=%"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - net-mysql
  mysql-exporter:
    image: prom/mysqld-exporter:v0.13.0
    container_name: mysql-exporter
    environment:
      - DATA_SOURCE_NAME=root:root@(mysql:3306)/
    ports:
      - 9104:9104
    networks:
      - net-mysql
    depends_on:
      - mysql
networks:
  net-mysql:
    driver: bridge