version: '3.7'
services:
  neo4j:
    image: neo4j:5.6.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
    networks:
      - net-neo4j
    environment:
      - "NEO4J_AUTH=none"
networks:
  net-neo4j:
    driver: bridge