version: '3.7'
services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - ./loki/data:/loki/data
    ports:
      - "3100:3100"
    networks:
      - net-loki
networks:
  net-loki:
    driver: bridge