version: '3.7'
services:
  grafana:
    image: grafana/grafana:7.5.10
    container_name: grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - net-grafana
networks:
  net-grafana:
    driver: bridge