version: "3.7"
services:
  clickhouse-node2-main:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: clickhouse-node2-main
    hostname: 172.16.2.231
    ports:
      - "3123:3123"
      - "3900:3900"
      - "3904:3904"
      - "3909:3909"
    volumes:
      - ./clickhouse/node2/main/data:/var/lib/clickhouse
      - ./clickhouse/node2/main/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/node1/main/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/node2/main/config/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse/node2/main/log:/var/log/clickhouse-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - net-ck-2
  clickhouse-node2-sub:
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    container_name: clickhouse-node2-sub
    hostname: 172.16.2.231
    ports:
      - "4123:4123"
      - "4900:4900"
      - "4904:4904"
      - "4909:4909"
    volumes:
      - ./clickhouse/node2/sub/data:/var/lib/clickhouse
      - ./clickhouse/node2/sub/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/node1/main/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/node2/sub/config/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse/node2/sub/log:/var/log/clickhouse-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - net-ck-2
networks:
  net-ck-2:
    driver: bridge