version: '3.7'
services:
  redis:
    image: redis:5.0
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/:/etc/redis/
    ports:
      - 6379:6379
    networks:
      - net-redis
networks:
  net-redis:
    driver: bridge