version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_ROOT_HOST=%"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    ports:
      - 3306:3306
    networks:
      - net-mysql
networks:
  net-mysql:
    driver: bridge