services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=martin-local"
      - "MYSQL_DATABASE=test-local"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net-mysql
  mysql-exporter:
    image: prom/mysqld-exporter:v0.13.0
    container_name: mysql-exporter
    environment:
      - DATA_SOURCE_NAME=root:martin-local@(mysql:3306)/
    ports:
      - "9104:9104"
    networks:
      - net-mysql
    depends_on:
      - mysql
networks:
  net-mysql:
    driver: bridge