version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2021-10-27T16-29-42Z
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniostorage
    volumes:
      - ./minio/data:/data
    command: server --console-address ':9001' /data
    networks:
      - net-minio
networks:
  net-minio:
    driver: bridge