version: '3.7'
services:
  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/:/etc/redis/
    ports:
      - "6379:6379"
    networks:
      - net-redis
  redis-exporter:
    image: oliver006/redis_exporter:v1.58.0
    container_name: redis-exporter
    command: [
      '--redis.password=',
      '--redis.addr=redis:6379'
    ]
    ports:
      - "9121:9121"
    networks:
      - net-redis
    depends_on:
      - redis
networks:
  net-redis:
    driver: bridge