version: "3.7"
services:
  clickhouse-2s-node1:
    image: clickhouse/clickhouse-server:22.12.3.5-alpine
    container_name: clickhouse-2s-node1
    hostname: 172.16.0.152
    ports:
      - "5123:5123"
      - "5900:5900"
      - "5904:5904"
      - "5909:5909"
    volumes:
      - ./clickhouse/2s/node1/data:/var/lib/clickhouse
      - ./clickhouse/2s/node1/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/2s/node1/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/2s/node1/config/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse/2s/node1/log:/var/log/clickhouse-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - net-ck-2s
  clickhouse-2s-node2:
    image: clickhouse/clickhouse-server:22.12.3.5-alpine
    container_name: clickhouse-2s-node2
    hostname: 172.16.0.152
    ports:
      - "6123:6123"
      - "6900:6900"
      - "6904:6904"
      - "6909:6909"
    volumes:
      - ./clickhouse/2s/node2/data:/var/lib/clickhouse
      - ./clickhouse/2s/node2/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/2s/node2/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/2s/node2/config/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse/2s/node2/log:/var/log/clickhouse-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - net-ck-2s
networks:
  net-ck-2s:
    driver: bridge