server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.16.2.231:3100/loki/api/v1/push

scrape_configs:
- job_name: springboot-job
  static_configs:
  - targets:
      - localhost
    labels:
      level: DEBUG
      __path__: /var/log/debug/debug.log
  - targets:
      - localhost
    labels:
      level: INFO
      __path__: /var/log/info/info.log
